### ISSUE TITLE
Executing error

### ISSUE THREAD

**Issue by SirSeran** [spring-guides/gs-rest-service#40]
Hey all,

While I was building and executing this getting started project I got a mistake that does not let me see the project executing I will copy my log and I hope you can help me to understand what I have done badly. I use the following commands in the complete directory:

sergio:complete$ ./gradlew build
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:findMainClass
:jar
:bootRepackage
:assemble
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:check UP-TO-DATE
:build

BUILD SUCCESSFUL

Total time: 4.772 secs
sergio:complete$ java -jar build/libs/gs-rest-service-0.1.0.jar
Exception in thread "main" java.lang.UnsupportedClassVersionError: hello/Application : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:142)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at java.lang.Thread.run(Thread.java:745

**Comment by gregturn** [comment]
What version of Java are you using?

**Comment by SirSeran** [comment]
sergio:complete$ java -version
java version "1.7.0_91"
OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)

**Comment by SirSeran** [comment]
My bad I realize the java recomended version is JDK 1.8. Now I download the proper jdk for this project but I cannot see yet the final result.
sergio:complete$ java 
sergio:complete$ java -version
java version "1.8.0_71"
Java(TM) SE Runtime Environment (build 1.8.0_71-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.71-b15, mixed mode)
sergio:complete$ ./gradlew build
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:findMainClass
:jar
:bootRepackage
:assemble
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:check UP-TO-DATE
:build

BUILD SUCCESSFUL

Total time: 5.106 secs


BUT once I execute java -jar build/libs/gs-rest-service-0.1.0.jar the execution get stucked just after the Started Application in 2.653 seconds (JVM running for 3.089).

Any tips?

**Comment by SirSeran** [comment]
I got even this message in my web browser:
http://localhost:8080/greetings

Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Sat Jan 23 10:21:19 COT 2016
There was an unexpected error (type=Not Found, status=404).
No message available

I am really sorry if I am asking stupid question but I have not found just by googling and this is my first time with Spring.

**Comment by gregturn** [comment]
Sorry if this is confusing, but you're actually doing all right.

1. It's not getting stuck. It is fully up and running.

2. The route is /greeting not /greetings. Try http://localhost:8080/greeting.

You can double check things by looking at the console output:

```
2016-01-23 10:04:14.605  INFO 2572 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/greeting]}" onto public hello.Greeting hello.GreetingController.greeting(java.lang.String)
2016-01-23 10:04:14.610  INFO 2572 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2016-01-23 10:04:14.610  INFO 2572 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.sp
```

**Comment by SirSeran** [comment]
It is working indeed.
Thank you a lot for the help.
