### ISSUE TITLE
Running into "org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class" 

### ISSUE THREAD

**Issue by saketh5** [spring-guides/gs-rest-service#48]
Hello Everyone, 
                            I am trying to run the spring-boot starter guide and when I try to run the DemoApplication.java as a spring boot app, I am running into the following exception. Can you please help me on resolving this issue. FYI: I am using STS as my IDE. 

  .   ____          _            __ _ _
 /\ / **_'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )_** | '_ | '_| | '_ \/ _` | \ \ \ \
 \/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .**|_| |_|_| |_\**, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.4.1.RELEASE)

2016-09-28 11:43:14.604  INFO 71255 --- [           main] com.example.DemoApplication              : Starting DemoApplication on MC02S45BBG8WP with PID 71255 (/Users/mpulipaka/Documents/workspace-sts-3.6.0.RELEASE/demo/target/classes started by mpulipaka in /Users/mpulipaka/Documents/workspace-sts-3.6.0.RELEASE/demo)
2016-09-28 11:43:14.607  INFO 71255 --- [           main] com.example.DemoApplication              : No active profile set, falling back to default profiles: default
2016-09-28 11:43:14.625  INFO 71255 --- [kground-preinit] org.hibernate.validator.util.Version     : Hibernate Validator 4.0.0.GA
2016-09-28 11:43:14.632  INFO 71255 --- [kground-preinit] o.h.v.e.r.DefaultTraversableResolver     : Instantiated an instance of org.hibernate.validator.engine.resolver.JPATraversableResolver.
2016-09-28 11:43:14.652  INFO 71255 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@1ab3a8c8: startup date [Wed Sep 28 11:43:14 PDT 2016]; root of context hierarchy
2016-09-28 11:43:14.953  WARN 71255 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration]; nested exception is java.lang.NoClassDefFoundError: org/springframework/data/repository/config/RepositoryConfigurationSource
2016-09-28 11:43:14.970 ERROR 71255 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration]; nested exception is java.lang.NoClassDefFoundError: org/springframework/data/repository/config/RepositoryConfigurationSource
    at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:548) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
    at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:286) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
    at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:237) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
    at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:539) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
    at org.springframework.context.annotation.ConfigurationClassParser.processDeferredImportSelectors(ConfigurationClassParser.java:482) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
    at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:191) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
    at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:324) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
    at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:246) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
    at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:273) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
    at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:98) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
    at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:681) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:523) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
    at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175) [spring-boot-1.4.1.RELEASE.jar:1.4.1.RELEASE]
    at com.example.DemoApplication.main(DemoApplication.java:11) [classes/:na]
Caused by: java.lang.NoClassDefFoundError: org/springframework/data/repository/config/RepositoryConfigurationSource
    at java.lang.Class.getDeclaredConstructors0(Native Method) ~[na:1.8.0_74]
    at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[na:1.8.0_74]
    at java.lang.Class.getConstructor0(Class.java:3075) ~[na:1.8.0_74]
    at java.lang.Class.getDeclaredConstructor(Class.java:2178) ~[na:1.8.0_74]
    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:102) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:125) ~[spring-beans-4.3.3.RELEASE.jar:4.3.3.RELEASE]
    at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:529) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
    ... 18 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.data.repository.config.RepositoryConfigurationSource
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_74]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_74]
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_74]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_74]
    ... 25 common frames omitted

**Comment by gregturn** [comment]
@saketh5 I'm not sure what you are running. None of them have a `DemoApplication.java`. The main runner for this guide is named `Application.java`, and I just downloaded it inside STS and it ran fine.
