### ISSUE TITLE
Can't build using Maven due to ClassNotFoundException: ch.qos.logback.classic.joran.JoranConfigurator

### ISSUE THREAD

**Issue by evere10** [spring-guides/gs-rest-service#51]
App is building okayish using Gradle.

Tried to run app using Maven and encountered error, log is here:

```
$ mvn spring-boot:run
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building gs-rest-service 0.1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> spring-boot-maven-plugin:1.4.2.RELEASE:run (default-cli) > test-compile @ gs-rest-service >>>
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ gs-rest-service ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /tmp/rest/complete/src/main/resources
[INFO] skip non existing resourceDirectory /tmp/rest/complete/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ gs-rest-service ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ gs-rest-service ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /tmp/rest/complete/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ gs-rest-service ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] <<< spring-boot-maven-plugin:1.4.2.RELEASE:run (default-cli) < test-compile @ gs-rest-service <<<
[INFO] 
[INFO] --- spring-boot-maven-plugin:1.4.2.RELEASE:run (default-cli) @ gs-rest-service ---
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[WARNING] 
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:506)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: ch/qos/logback/classic/joran/JoranConfigurator
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getConstructor(Class.java:1825)
	at org.springframework.boot.logging.LoggingSystem.get(LoggingSystem.java:126)
	at org.springframework.boot.logging.LoggingSystem.get(LoggingSystem.java:117)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationStartedEvent(LoggingApplicationListener.java:225)
	at org.springframework.boot.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:205)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:121)
	at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:63)
	at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:48)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175)
	at hello.Application.main(Application.java:10)
	... 6 more
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.classic.joran.JoranConfigurator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 23 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.044 s
[INFO] Finished at: 2016-11-12T21:01:32+03:00
[INFO] Final Memory: 20M/176M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.4.2.RELEASE:run (default-cli) on project gs-rest-service: An exception occurred while running. null: InvocationTargetException: ch/qos/logback/classic/joran/JoranConfigurator: ch.qos.logback.classic.joran.JoranConfigurator -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by gregturn** [comment]
Works for me:

```
$ cd /tmp
retina:tmp gturnquist$ git clone https://github.com/spring-guides/gs-rest-service.git
Cloning into 'gs-rest-service'...
remote: Counting objects: 1506, done.
remote: Total 1506 (delta 0), reused 0 (delta 0), pack-reused 1506
Receiving objects: 100% (1506/1506), 815.43 KiB | 757.00 KiB/s, done.
Resolving deltas: 100% (792/792), done.
Checking connectivity... done.
retina:tmp gturnquist$ cd gs-rest-service
retina:gs-rest-service gturnquist$ cd complete
retina:complete gturnquist$ SERVER_PORT=7000 mvn clean spring-boot:run
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building gs-rest-service 0.1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ gs-rest-service ---
[INFO] Deleting /private/tmp/gs-rest-service/complete/target
[INFO] 
[INFO] >>> spring-boot-maven-plugin:1.4.2.RELEASE:run (default-cli) > test-compile @ gs-rest-service >>>
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ gs-rest-service ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /private/tmp/gs-rest-service/complete/src/main/resources
[INFO] skip non existing resourceDirectory /private/tmp/gs-rest-service/complete/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ gs-rest-service ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /private/tmp/gs-rest-service/complete/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ gs-rest-service ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /private/tmp/gs-rest-service/complete/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ gs-rest-service ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /private/tmp/gs-rest-service/complete/target/test-classes
[INFO] 
[INFO] <<< spring-boot-maven-plugin:1.4.2.RELEASE:run (default-cli) < test-compile @ gs-rest-service <<<
[INFO] 
[INFO] --- spring-boot-maven-plugin:1.4.2.RELEASE:run (default-cli) @ gs-rest-service ---

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.4.2.RELEASE)

2016-11-12 12:18:14.212  INFO 95264 --- [           main] hello.Application                        : Starting Application on retina with PID 95264 (/private/tmp/gs-rest-service/complete/target/classes started by gturnquist in /private/tmp/gs-rest-service/complete)
2016-11-12 12:18:14.213  INFO 95264 --- [           main] hello.Application                        : No active profile set, falling back to default profiles: default
2016-11-12 12:18:14.261  INFO 95264 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@263bd8ad: startup date [Sat Nov 12 12:18:14 CST 2016]; root of context hierarchy
2016-11-12 12:18:15.120  INFO 95264 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 7000 (http)
2016-11-12 12:18:15.130  INFO 95264 --- [           main] o.apache.catalina.core.StandardService   : Starting service Tomcat
2016-11-12 12:18:15.130  INFO 95264 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.6
2016-11-12 12:18:15.201  INFO 95264 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2016-11-12 12:18:15.201  INFO 95264 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 944 ms
2016-11-12 12:18:15.341  INFO 95264 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Mapping servlet: 'dispatcherServlet' to [/]
2016-11-12 12:18:15.345  INFO 95264 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2016-11-12 12:18:15.345  INFO 95264 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2016-11-12 12:18:15.345  INFO 95264 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2016-11-12 12:18:15.345  INFO 95264 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2016-11-12 12:18:15.573  INFO 95264 --- [           main] s.w.s.m.m.a.RequestMappingHandlerAdapter : Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@263bd8ad: startup date [Sat Nov 12 12:18:14 CST 2016]; root of context hierarchy
2016-11-12 12:18:15.623  INFO 95264 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/greeting]}" onto public hello.Greeting hello.GreetingController.greeting(java.lang.String)
2016-11-12 12:18:15.626  INFO 95264 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2016-11-12 12:18:15.626  INFO 95264 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2016-11-12 12:18:15.652  INFO 95264 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2016-11-12 12:18:15.652  INFO 95264 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2016-11-12 12:18:15.687  INFO 95264 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2016-11-12 12:18:15.801  INFO 95264 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2016-11-12 12:18:15.852  INFO 95264 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 7000 (http)
2016-11-12 12:18:15.858  INFO 95264 --- [           main] hello.Application                        : Started Application in 1.946 seconds (JVM running for 4.646)
```

**Comment by dsyer** [comment]
Bad jar? Hotel wifi? Clear your cache?

**Comment by evere10** [comment]
@dsyer thanks for suggestion, building works after cache clearing. Sorry for inconvenience guys
