### ISSUE TITLE
Error in my program

### ISSUE THREAD

**Issue by Deobrat811** [spring-guides/gs-rest-service#64]
Even though ApplicationEvent class is there in Maven dependency but don't know why it's showing error
Exception in thread "main" java.lang.NoClassDefFoundError: org/springframework/context/ApplicationEvent
	at hello.Application.main(Application.java:10)
Caused by: java.lang.ClassNotFoundException: org.springframework.context.ApplicationEvent
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
Please help me

**Comment by saket700** [comment]
I think you're just missing the spring-context dependency.
Try add this one to your pom:
<dependency>
    <groupId>org.springframework</groupId>
    <artifactId>spring-context</artifactId>
</dependency>
or check with any other dependency, its a dependency issue, so its unavailable to load the dependency from that class.

**Comment by dsyer** [comment]
Probably a bad jar file. Clearing local caches and running again probably fixed it.
